### ISSUE TITLE
Only first 100 items get highlighted

### ISSUE THREAD

**Issue by mikelue** [Shougo/ddu-source-vim#1]
I am using "_func_" property of "_sourceParams_" with this plugin to provide my list of items.
And I also set "_highlights_" of  item attribute.

But there is _**only first 100 get highlighted**_, the rest are plain.

What do I miss for making all of the items get highlighted？

Any response would be appreciated.

![screenshot](https://github.com/Shougo/ddu-source-vim/assets/556726/03d73d81-273d-4c80-bc6d-0b7f54a33d6a)
<hr/>

sample of how I build "item":
```
{
    kind: 'word',
    word: aliasLine,
    display: display,
    data: {
        alias: aliasAndSourceCommand[1],
        sourceCommand: aliasAndSourceCommand[2],
    },
    highlights: [
        {
            name: "ddu-git-alias-command",
            hl_group: "Typedef",
            col: 1, width: aliasAndSourceCommand[1]->len()
        },
        {
            name: "ddu-git-alias-sourceCommand",
            hl_group: "String",
            col: sourceCommandPos[1],
            width: sourceCommandPos[2] - sourceCommandPos[1] + 1
        },
    ]
}
``` 

- My VIM:  `9.0.1600`, with _vim9script_

**Comment by Shougo** [comment]
Please see this.  It is UI's feature.

```
                                           *ddu-ui-ff-param-maxHighlightItems*
maxHighlightItems (number)
		The maximum number of highlighted items.
		NOTE: If you increase the param, the UI will be slower.

		Default: 100
```

**Comment by mikelue** [comment]
Thanks 😄
